# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\My Data\01 My Code\python\SanTools\W_ItemTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormItemTable(object):
    def setupUi(self, FormItemTable):
        FormItemTable.setObjectName("FormItemTable")
        FormItemTable.resize(161, 224)
        FormItemTable.setAcceptDrops(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormItemTable)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelItemsName = QtWidgets.QLabel(FormItemTable)
        self.labelItemsName.setObjectName("labelItemsName")
        self.horizontalLayout.addWidget(self.labelItemsName)
        self.lineEditItemsFilter = QtWidgets.QLineEdit(FormItemTable)
        self.lineEditItemsFilter.setObjectName("lineEditItemsFilter")
        self.horizontalLayout.addWidget(self.lineEditItemsFilter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableViewItems = DragableTableView(FormItemTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewItems.sizePolicy().hasHeightForWidth())
        self.tableViewItems.setSizePolicy(sizePolicy)
        self.tableViewItems.setMinimumSize(QtCore.QSize(100, 180))
        self.tableViewItems.setAcceptDrops(True)
        self.tableViewItems.setDragEnabled(True)
        self.tableViewItems.setDragDropOverwriteMode(False)
        self.tableViewItems.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableViewItems.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableViewItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewItems.setSortingEnabled(True)
        self.tableViewItems.setObjectName("tableViewItems")
        self.tableViewItems.horizontalHeader().setCascadingSectionResizes(True)
        self.tableViewItems.horizontalHeader().setStretchLastSection(True)
        self.tableViewItems.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.tableViewItems)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormItemTable)
        QtCore.QMetaObject.connectSlotsByName(FormItemTable)

    def retranslateUi(self, FormItemTable):
        _translate = QtCore.QCoreApplication.translate
        FormItemTable.setWindowTitle(_translate("FormItemTable", "Form"))
        self.labelItemsName.setText(_translate("FormItemTable", "武将库"))
        self.lineEditItemsFilter.setPlaceholderText(_translate("FormItemTable", "搜索"))
from DragableTableView import DragableTableView
