# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\My Code\python\SanTools\DesignerFile\SanTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollAreaLibs = QtWidgets.QScrollArea(self.splitter)
        self.scrollAreaLibs.setWidgetResizable(True)
        self.scrollAreaLibs.setObjectName("scrollAreaLibs")
        self.scrollAreaWidgetLibs = QtWidgets.QWidget()
        self.scrollAreaWidgetLibs.setGeometry(QtCore.QRect(0, 0, 392, 378))
        self.scrollAreaWidgetLibs.setObjectName("scrollAreaWidgetLibs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetLibs)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutLibs = QtWidgets.QVBoxLayout()
        self.verticalLayoutLibs.setObjectName("verticalLayoutLibs")
        self.verticalLayout_2.addLayout(self.verticalLayoutLibs)
        self.scrollAreaLibs.setWidget(self.scrollAreaWidgetLibs)
        self.scrollAreaTeams = QtWidgets.QScrollArea(self.splitter)
        self.scrollAreaTeams.setWidgetResizable(True)
        self.scrollAreaTeams.setObjectName("scrollAreaTeams")
        self.scrollAreaWidgetTeams = QtWidgets.QWidget()
        self.scrollAreaWidgetTeams.setGeometry(QtCore.QRect(0, 0, 392, 378))
        self.scrollAreaWidgetTeams.setObjectName("scrollAreaWidgetTeams")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetTeams)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutTeams = QtWidgets.QVBoxLayout()
        self.verticalLayoutTeams.setObjectName("verticalLayoutTeams")
        self.verticalLayout_3.addLayout(self.verticalLayoutTeams)
        self.scrollAreaTeams.setWidget(self.scrollAreaWidgetTeams)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
