# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\hupei\Documents\GitHub\SanTools\DesignerFile\Member.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMember(object):
    def setupUi(self, FormMember):
        FormMember.setObjectName("FormMember")
        FormMember.resize(142, 106)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormMember.sizePolicy().hasHeightForWidth())
        FormMember.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(FormMember)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelHeroName = DropableLabel(FormMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHeroName.sizePolicy().hasHeightForWidth())
        self.labelHeroName.setSizePolicy(sizePolicy)
        self.labelHeroName.setMinimumSize(QtCore.QSize(120, 25))
        self.labelHeroName.setBaseSize(QtCore.QSize(120, 25))
        self.labelHeroName.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelHeroName.setLineWidth(1)
        self.labelHeroName.setMidLineWidth(0)
        self.labelHeroName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeroName.setObjectName("labelHeroName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.labelHeroName)
        self.labelMagic1 = QtWidgets.QLabel(FormMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagic1.sizePolicy().hasHeightForWidth())
        self.labelMagic1.setSizePolicy(sizePolicy)
        self.labelMagic1.setMinimumSize(QtCore.QSize(120, 25))
        self.labelMagic1.setBaseSize(QtCore.QSize(120, 25))
        self.labelMagic1.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelMagic1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMagic1.setObjectName("labelMagic1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.labelMagic1)
        self.labelMagic2 = DropableLabel(FormMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagic2.sizePolicy().hasHeightForWidth())
        self.labelMagic2.setSizePolicy(sizePolicy)
        self.labelMagic2.setMinimumSize(QtCore.QSize(120, 25))
        self.labelMagic2.setBaseSize(QtCore.QSize(120, 25))
        self.labelMagic2.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelMagic2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMagic2.setObjectName("labelMagic2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.labelMagic2)
        self.labelMagic3 = DropableLabel(FormMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagic3.sizePolicy().hasHeightForWidth())
        self.labelMagic3.setSizePolicy(sizePolicy)
        self.labelMagic3.setMinimumSize(QtCore.QSize(120, 25))
        self.labelMagic3.setBaseSize(QtCore.QSize(120, 25))
        self.labelMagic3.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelMagic3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMagic3.setObjectName("labelMagic3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.labelMagic3)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(FormMember)
        QtCore.QMetaObject.connectSlotsByName(FormMember)

    def retranslateUi(self, FormMember):
        _translate = QtCore.QCoreApplication.translate
        FormMember.setWindowTitle(_translate("FormMember", "Form"))
        self.labelHeroName.setText(_translate("FormMember", "武将"))
        self.labelMagic1.setText(_translate("FormMember", "战法一"))
        self.labelMagic2.setText(_translate("FormMember", "战法二"))
        self.labelMagic3.setText(_translate("FormMember", "战法三"))
from Components import DropableLabel
