# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\hupei\Documents\GitHub\SanTools\DesignerFile\Team.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTeam(object):
    def setupUi(self, FormTeam):
        FormTeam.setObjectName("FormTeam")
        FormTeam.resize(445, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormTeam.sizePolicy().hasHeightForWidth())
        FormTeam.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(FormTeam)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTeamNo = QtWidgets.QLabel(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamNo.sizePolicy().hasHeightForWidth())
        self.labelTeamNo.setSizePolicy(sizePolicy)
        self.labelTeamNo.setObjectName("labelTeamNo")
        self.horizontalLayout.addWidget(self.labelTeamNo)
        self.comboBoxType = QtWidgets.QComboBox(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxType.sizePolicy().hasHeightForWidth())
        self.comboBoxType.setSizePolicy(sizePolicy)
        self.comboBoxType.setObjectName("comboBoxType")
        self.horizontalLayout.addWidget(self.comboBoxType)
        self.lineEditTeamDesc = QtWidgets.QLineEdit(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTeamDesc.sizePolicy().hasHeightForWidth())
        self.lineEditTeamDesc.setSizePolicy(sizePolicy)
        self.lineEditTeamDesc.setObjectName("lineEditTeamDesc")
        self.horizontalLayout.addWidget(self.lineEditTeamDesc)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widgetMember1 = FormMember(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMember1.sizePolicy().hasHeightForWidth())
        self.widgetMember1.setSizePolicy(sizePolicy)
        self.widgetMember1.setObjectName("widgetMember1")
        self.horizontalLayout_2.addWidget(self.widgetMember1)
        self.widgetMember2 = FormMember(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMember2.sizePolicy().hasHeightForWidth())
        self.widgetMember2.setSizePolicy(sizePolicy)
        self.widgetMember2.setObjectName("widgetMember2")
        self.horizontalLayout_2.addWidget(self.widgetMember2)
        self.widgetMember3 = FormMember(FormTeam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMember3.sizePolicy().hasHeightForWidth())
        self.widgetMember3.setSizePolicy(sizePolicy)
        self.widgetMember3.setObjectName("widgetMember3")
        self.horizontalLayout_2.addWidget(self.widgetMember3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(FormTeam)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(FormTeam)
        QtCore.QMetaObject.connectSlotsByName(FormTeam)

    def retranslateUi(self, FormTeam):
        _translate = QtCore.QCoreApplication.translate
        FormTeam.setWindowTitle(_translate("FormTeam", "Form"))
        self.labelTeamNo.setText(_translate("FormTeam", "第一队"))
        self.lineEditTeamDesc.setPlaceholderText(_translate("FormTeam", "描述"))
from FormMember import FormMember
